User.create(first_name: "Kay", last_name: "Mok", email: "kay@example.com", password: "password", birthday: Time.at(rand * Time.now.to_i), username: "mokaymokay")
User.create(first_name: "Chris", last_name: "Holt", email: "cwh@example.com", password: "Password", birthday: Time.at(rand * Time.now.to_i), username: "cwholt")
Post.create(quote: "there is nothing to explain: just be, and live.", author: "manzoni", user_id: 1)
Post.create(quote: "the only constant in a world of tremendous change is the swift passage of time.", author: "cixin liu", user_id: 2)
Tag.create(content: "life")
Tag.create(content: "philosophy")
Tag.create(content: "time")
Tagging.create(post_id: 1, tag_id: 1)
Tagging.create(post_id: 1, tag_id: 2)
Tagging.create(post_id: 2, tag_id: 1)
Tagging.create(post_id: 2, tag_id: 3)
